/**
 * build.mjs
 * -----------------------------------------------------------------------------
 * Bundles the ES-module source graph into a single minified IIFE and inlines it
 * into index.html, producing the self-contained Skydoku.html that runs from
 * file:// inside an Android WebView (no cross-origin module loads).
 *
 *   node scripts/build.mjs
 * -----------------------------------------------------------------------------
 */
import esbuild from 'esbuild';
const { build } = esbuild;
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, extname, basename } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// --- Asset packing --------------------------------------------------------
// Inline every file in assets/sprites/ as a base64 data URI into a generated
// module, so the single-file build stays fully self-contained (no file:// or
// network image loads inside the Android WebView). Runs before esbuild bundles.
function packAssets() {
  const dir = resolve(root, 'assets/sprites');
  const mime = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp' };
  const entries = existsSync(dir) ? readdirSync(dir).filter((f) => mime[extname(f).toLowerCase()]) : [];
  const lines = entries.map((f) => {
    const b64 = readFileSync(resolve(dir, f)).toString('base64');
    const key = basename(f, extname(f));               // e.g. gem_emerald
    return `  ${JSON.stringify(key)}: ${JSON.stringify(`data:${mime[extname(f).toLowerCase()]};base64,${b64}`)},`;
  });
  const out = `// AUTO-GENERATED by scripts/build.mjs — do not edit.\n// Sprite assets inlined as data URIs (keeps the single-file build self-contained).\nexport const ASSETS = Object.freeze({\n${lines.join('\n')}\n});\n`;
  writeFileSync(resolve(root, 'src/generated/assets.js'), out);
  console.log(`packed ${entries.length} sprite(s) -> src/generated/assets.js`);
}
packAssets();

const result = await build({
  entryPoints: [resolve(root, 'src/main.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2019',
  write: false,
  legalComments: 'none',
});
const js = result.outputFiles[0].text;

const html = readFileSync(resolve(root, 'index.html'), 'utf8');
// Replace the module <script src> with the inlined bundle, preserving the rest
// of the document (viewport meta, immersive-fullscreen bootstrap, styles).
const out = html.replace(
  /<script type="module" src="\.\/src\/main\.js"><\/script>/,
  `<script>${js}</script>`,
);
if (out === html) throw new Error('build: could not find module script tag to inline');

writeFileSync(resolve(root, 'Skydoku.html'), out);
// Also emit the Capacitor web root (webDir: "www") so `cap sync` copies the
// game into the Android app. index.html is what Capacitor loads.
const wwwDir = resolve(root, 'www');
if (!existsSync(wwwDir)) mkdirSync(wwwDir, { recursive: true });
writeFileSync(resolve(wwwDir, 'index.html'), out);
console.log(`built Skydoku.html + www/index.html (${(out.length / 1024).toFixed(0)}kb)`);
